'use client'

import { OutcomeAssessmentForm, OutcomeAssessmentSummary } from './warning-response-fields'
import { ImportPreview } from './import-preview'
import type { OutcomeAssessment, WarningResponse } from '@/lib/domain/warning-response'
import { ScopeReviewFields } from './scope-review-fields'

import {postJson as jsonPost} from '@/lib/http'
import { useRef, useState, type FormEvent } from 'react'
import { useRouter } from 'next/navigation'
import { CheckCircle2, Flag, Play, Send, Trophy, UploadCloud, XCircle } from 'lucide-react'
import type { Estimate, FindingOutcomeVerdict, LifecycleStatus } from '@/lib/domain/types'


export function LifecycleActions({estimate}:{estimate:Estimate}){
  const router=useRouter();const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[amount,setAmount]=useState(String(estimate.submittedAmount??estimate.estimatedTotal));const[note,setNote]=useState('')
  async function move(to:LifecycleStatus,opts?:{amount?:number;note?:string}){setBusy(true);setError('');try{await jsonPost(`/api/estimates/${estimate.id}/lifecycle`,{to,...opts});router.refresh()}catch(e){setError(e instanceof Error?e.message:'Could not update lifecycle.')}finally{setBusy(false)}}
  if(estimate.lifecycleStatus==='draft')return <div className="card lifecycle-card"><div className="eyebrow">Next commercial step</div><h3>Finish preflight review</h3><p className="subtle">Resolve or dismiss every finding and answer every open question. Then lock the reviewed bid before submission.</p>{estimate.status==='ready'?<button className="btn primary" disabled={busy} onClick={()=>move('reviewed')}><CheckCircle2 size={15}/>{busy?'Saving…':'Mark review complete'}</button>:<div className="helper">Preflight is not ready yet.</div>}{error&&<div className="error">{error}</div>}</div>
  if(estimate.lifecycleStatus==='reviewed')return <div className="card lifecycle-card"><div className="eyebrow">{estimate.status==='ready'?'Ready to submit':'Review changed'}</div><h3>{estimate.status==='ready'?'Record the submitted bid':'Resolve the new preflight work first'}</h3>{estimate.status==='ready'?<><div className="field"><label>Submitted amount</label><input type="number" min="1" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></div><button className="btn primary" disabled={busy||!Number(amount)} onClick={()=>move('submitted',{amount:Number(amount)})}><Send size={15}/>{busy?'Saving…':'Mark submitted'}</button></>:<p className="subtle">A rerun found unresolved findings or questions. Submission is database-blocked until the preflight returns to ready.</p>}{error&&<div className="error">{error}</div>}</div>
  if(estimate.lifecycleStatus==='submitted')return <div className="card lifecycle-card"><div className="eyebrow">Bid outcome</div><h3>What happened?</h3><div className="field"><label>Contract value if won</label><input type="number" min="1" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></div><div className="field"><label>Loss reason (optional)</label><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Price, schedule, no award, unknown…"/></div><div className="actions"><button className="btn primary" disabled={busy||!Number(amount)} onClick={()=>move('won',{amount:Number(amount)})}><Trophy size={15}/>Won</button><button className="btn" disabled={busy} onClick={()=>move('lost',{note})}><XCircle size={15}/>Lost</button></div>{error&&<div className="error">{error}</div>}</div>
  if(estimate.lifecycleStatus==='won')return <div className="card lifecycle-card"><div className="eyebrow">Awarded</div><h3>Start tracking field outcome</h3><p className="subtle">When work begins, move this estimate into execution. The original preflight stays frozen for later comparison.</p><button className="btn primary" disabled={busy} onClick={()=>move('in_progress')}><Play size={15}/>Start work</button>{error&&<div className="error">{error}</div>}</div>
  if(estimate.lifecycleStatus==='in_progress')return <div className="card lifecycle-card"><div className="eyebrow">In progress</div><h3>Close the field work</h3><p className="subtle">Mark completed only when final actual costs and labor can be imported.</p><button className="btn primary" disabled={busy} onClick={()=>move('completed')}><Flag size={15}/>Mark work completed</button>{error&&<div className="error">{error}</div>}</div>
  if(estimate.lifecycleStatus==='completed')return <div className="card lifecycle-card"><div className="eyebrow">Completed</div><h3>Import final actuals below</h3><p className="subtle">This creates the linked completed job, calculates variance, evaluates the original warnings, and prepares lessons for human review.</p></div>
  if(estimate.lifecycleStatus==='learning_review')return <div className="card lifecycle-card"><div className="eyebrow">Learning review</div><h3>Verify what Margin Memory learned</h3><p className="subtle">Confirm warning outcomes and approve/reject every proposed lesson. The lifecycle closes automatically when nothing remains pending.</p></div>
  if(estimate.lifecycleStatus==='lost')return <div className="card lifecycle-card"><div className="eyebrow">Lost bid</div><h3>Lifecycle closed</h3><p className="subtle">{estimate.lostReason?`Recorded reason: ${estimate.lostReason}`:'No loss reason was recorded.'}</p></div>
  return <div className="card lifecycle-card"><div className="eyebrow">Learning complete</div><h3>This job has closed the loop.</h3><p className="subtle">Verified warning outcomes and confirmed/rejected lessons are now part of company history.</p></div>
}

export function CloseoutActualsForm({estimateId}:{estimateId:string}){
  const router=useRouter();const formRef=useRef<HTMLFormElement>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[warning,setWarning]=useState('');const[previewReady,setPreviewReady]=useState(false);const[previewRevision,setPreviewRevision]=useState(0)
  function fileChanged(){setPreviewReady(false);setPreviewRevision(value=>value+1)}
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!previewReady){setError('Preview the actual-cost file and review any limitations before closeout.');return}setBusy(true);setError('');setWarning('');const form=new FormData(e.currentTarget);try{const res=await fetch(`/api/estimates/${estimateId}/closeout`,{method:'POST',body:form});const data=await res.json();if(!res.ok)throw new Error(data.error||'Could not import actuals.');setWarning((data.warnings??[]).join(' '));router.refresh()}catch(err){setError(err instanceof Error?err.message:'Could not import actuals.')}finally{setBusy(false)}}
  return <form ref={formRef} className="card form-card closeout-form" onSubmit={submit}><input type="hidden" name="estimateId" value={estimateId}/><div className="eyebrow">Actuals → learning</div><h2>Close out this job</h2><div className="form-grid"><div className="field full"><label>Final actual-cost spreadsheet</label><div className="file-drop"><input name="actualFile" type="file" accept=".xlsx,.csv" required onChange={fileChanged}/><div className="helper">Use the final job-cost export with actual cost and actual hours where available.</div></div></div><ImportPreview key={previewRevision} formRef={formRef} mode="actual" onReady={setPreviewReady}/><ScopeReviewFields/><div className="field full"><label>Closeout notes</label><textarea name="notes" placeholder="What changed? Access, scope, supplier, crew productivity, shutdowns, rework…"/></div><div className="field full"><label>Closeout notes file (optional)</label><div className="file-drop"><input name="notesFile" type="file" accept=".pdf,.txt,.md" onChange={fileChanged}/></div></div></div>{error&&<div className="error">{error}</div>}{warning&&<div className="warning-banner">{warning}</div>}<button className="btn primary" disabled={busy}><UploadCloud size={16}/>{busy?'Closing out…':'Import actuals and learn'}</button></form>
}

export function FindingOutcomeActions({outcomeId,current,assessment,responses}:{outcomeId:string;current?:FindingOutcomeVerdict;assessment?:OutcomeAssessment;responses:WarningResponse[]}){
  const router=useRouter()
  if(assessment)return <OutcomeAssessmentSummary assessment={assessment}/>
  if(current)return <div className="helper">Confirmed: <strong>{current.replaceAll('_',' ')}</strong> · No separate response assessment was recorded.</div>
  return <OutcomeAssessmentForm responses={responses} onSave={async assessment=>{await jsonPost(`/api/finding-outcomes/${outcomeId}/confirm`,{assessment});router.refresh()}}/>
}
