import {it,expect} from 'vitest'
import {EvidenceLedger,calculateRisk,isActionRelevantToCategory,renderAgentOutput,type ToolEvidence} from '../src/lib/agent/provenance'
import {seedStore} from '../src/lib/seed'
const job={...seedStore.jobs[0],id:crypto.randomUUID()}
const secondJob={...job,id:crypto.randomUUID(),name:`${job.name} comparison`}
async function fixture(){const saved:ToolEvidence[]=[];const ledger=new EvidenceLedger(crypto.randomUUID(),async e=>{saved.push(e)});await ledger.record({kind:'search',toolName:'search_similar_jobs',result:{jobIds:[job.id,secondJob.id]}});const calc=await ledger.record({kind:'calculation',toolName:'calculate_category_risk',result:calculateRisk([job,secondJob],'labor')});const raw={findings:[{category:'labor',severity:'high',action:'access',calculationRefs:[calc.id],jobEvidenceRefs:[] as string[]}],questions:[]};return{ledger,raw,saved,calc}}
it('rejects unknown calculation IDs',async()=>{const{ledger,raw}=await fixture();raw.findings[0].calculationRefs=[crypto.randomUUID()];expect(()=>renderAgentOutput(raw,ledger)).toThrow()})
it('rejects calculations from another investigation',async()=>{const a=await fixture();const b=await fixture();a.raw.findings[0].calculationRefs=[b.calc.id];expect(()=>renderAgentOutput(a.raw,a.ledger)).toThrow()})
it('rejects multiple calculation references because one calculation owns each rendered claim',async()=>{const{ledger,raw,calc}=await fixture();raw.findings[0].calculationRefs=[calc.id,calc.id];expect(()=>renderAgentOutput(raw,ledger)).toThrow()})
it('rejects arbitrary job refs and unsearched jobs',async()=>{const{ledger,raw}=await fixture();raw.findings[0].jobEvidenceRefs=[job.id];expect(()=>renderAgentOutput(raw,ledger)).toThrow();const empty=new EvidenceLedger(crypto.randomUUID(),async()=>{});await empty.record({kind:'search',toolName:'search_similar_jobs',result:{jobIds:[]}});const calc=await empty.record({kind:'calculation',toolName:'calculate_category_risk',result:calculateRisk([job,secondJob],'labor')});raw.findings[0].jobEvidenceRefs=[];raw.findings[0].calculationRefs=[calc.id];expect(()=>renderAgentOutput(raw,empty)).toThrow('not retrieved')})
it('renders facts only from persisted calculations and rejects numerical overrides',async()=>{const{ledger,raw,saved}=await fixture();const output=renderAgentOutput(raw,ledger);expect(output.findings[0].claim).toBe('2 of 2 completed jobs exceeded the scope-adjusted labor budget by more than 5%.');expect(saved).toHaveLength(2);expect(()=>renderAgentOutput({...raw,findings:[{...raw.findings[0],claim:'5 of 7 jobs overran 23%'}]},ledger)).toThrow()})
it('renders evidence strength and its limitation from the deterministic calculation',async()=>{const{ledger,raw}=await fixture();const output=renderAgentOutput(raw,ledger);expect(output.findings[0].rationale).toContain('Evidence strength: Limited.');expect(output.findings[0].rationale).toContain('not a calibrated probability')})
it('does not accept output unless evidence persistence succeeds',async()=>{const ledger=new EvidenceLedger(crypto.randomUUID(),async()=>{throw new Error('database down')});await expect(ledger.record({kind:'search',toolName:'search_similar_jobs',result:{jobIds:[job.id]}})).rejects.toThrow('database down');expect(ledger.all()).toEqual([])})
it('ledger snapshots cannot be mutated by tool consumers',async()=>{const{ledger,calc}=await fixture();if(calc.kind!=='calculation')throw new Error('wrong kind');calc.result.overrunCount=99;const stored=ledger.get(calc.id);expect(stored.kind==='calculation'&&stored.result.overrunCount).toBe(2)})
it('binds a contributing lesson to the exact persisted search evidence',async()=>{const{ledger,raw}=await fixture();const lesson=await ledger.record({kind:'search',toolName:'search_lessons',result:{jobIds:[job.id],lessonIds:[crypto.randomUUID()],query:'occupied access'}});const finding={...raw.findings[0],lessonEvidenceRefs:[lesson.id]};expect(renderAgentOutput({...raw,findings:[finding]},ledger).findings[0].evidenceRefs).toContain(lesson.id);finding.lessonEvidenceRefs=[crypto.randomUUID()];expect(()=>renderAgentOutput({...raw,findings:[finding]},ledger)).toThrow('foreign')})
it('resolves an exact retrieved lesson ID to its persisted current-investigation search evidence',async()=>{const{ledger,raw}=await fixture();const lessonId=crypto.randomUUID();const search=await ledger.record({kind:'search',toolName:'search_lessons',result:{jobIds:[job.id],lessonIds:[lessonId],query:'occupied access'}});const finding={...raw.findings[0],lessonEvidenceRefs:[lessonId]};expect(renderAgentOutput({...raw,findings:[finding]},ledger).findings[0].evidenceRefs).toContain(search.id)})
it('resolves an inspected job ID but continues to reject an uninspected job ID',async()=>{const{ledger,raw}=await fixture();const inspection=await ledger.record({kind:'inspection',toolName:'inspect_job',result:{jobId:job.id,name:job.name,variances:job.variances}});const finding={...raw.findings[0],jobEvidenceRefs:[job.id]};expect(renderAgentOutput({...raw,findings:[finding]},ledger).findings[0].evidenceRefs).toContain(inspection.id);finding.jobEvidenceRefs=[crypto.randomUUID()];expect(()=>renderAgentOutput({...raw,findings:[finding]},ledger)).toThrow('foreign')})
it('does not turn a calculation with no material historical overrun into a finding',async()=>{
 const{ledger,raw,calc}=await fixture();if(calc.kind!=='calculation')throw new Error('wrong evidence kind')
 calc.result.overrunCount=0;calc.result.overrunFrequency=0;calc.result.medianVariancePct=0.014;calc.result.maximumVariancePct=0.023
 const replacement=new EvidenceLedger(ledger.investigationId,async()=>{})
 await replacement.record({kind:'search',toolName:'search_similar_jobs',result:{jobIds:[job.id,secondJob.id]}})
 const persisted=await replacement.record({kind:'calculation',toolName:'calculate_category_risk',result:calc.result})
 raw.findings[0].calculationRefs=[persisted.id]
 expect(renderAgentOutput(raw,replacement)).toMatchObject({findings:[],summary:'No material historical risks found.'})
})
it('does not present a supplier-pricing action for a labor calculation',async()=>{
 const{ledger,raw}=await fixture();raw.findings[0].action='pricing'
 expect(renderAgentOutput(raw,ledger).findings[0]).toMatchObject({title:'Review category allowance',recommendation:'Review the category allowance against the completed-job evidence.'})
})
it('keeps question and finding actions professionally relevant to their category',()=>{expect(isActionRelevantToCategory('labor','pricing')).toBe(false);expect(isActionRelevantToCategory('materials','pricing')).toBe(true);expect(isActionRelevantToCategory('labor','access')).toBe(true)})
it('rejects a false clean result that never searched comparable jobs',async()=>{const ledger=new EvidenceLedger(crypto.randomUUID(),async()=>{});expect(()=>renderAgentOutput({findings:[],questions:[]},ledger)).toThrow('comparable-job search evidence')})
