import { WarningResponseHistory } from '@/components/warning-response-fields'
import {MemoryReadiness} from '@/components/memory-readiness'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { AlertTriangle, CheckCircle2, Clock3, ExternalLink, ShieldCheck } from 'lucide-react'
import { AnswerQuestion, FindingActions, PostSubmissionResponse, LessonActions, RerunReview } from '@/components/actions'
import { CloseoutActualsForm, FindingOutcomeActions, LifecycleActions } from '@/components/lifecycle-actions'
import { Badge } from '@/components/ui'
import { money } from '@/lib/domain/analytics'
import type { LifecycleStatus } from '@/lib/domain/types'
import {isDemoOrigin} from '@/lib/domain/demo'
import { getEstimate, getEstimateLifecycleEvents, listDocuments, readStore } from '@/lib/repository/store'

export const dynamic='force-dynamic'
const stages:LifecycleStatus[]=['draft','reviewed','submitted','won','in_progress','completed','learning_review','learned']
const stageLabel=(x:LifecycleStatus)=>({draft:'Draft',reviewed:'Reviewed',submitted:'Submitted',won:'Won',lost:'Lost',in_progress:'In progress',completed:'Completed',learning_review:'Learning review',learned:'Learned'}[x])

export default async function EstimatePage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{warning?:string}>}){
  const {id}=await params;const query=await searchParams
  const [estimate,documents,store,events]=await Promise.all([getEstimate(id),listDocuments({estimateId:id}),readStore(),getEstimateLifecycleEvents(id)])
  if(!estimate)notFound()
  const submittedWarnings=estimate.findings.filter(f=>estimate.submittedFindingIds.includes(f.id))
  const open=estimate.findings.filter(x=>x.status==='open');const riskScore=Math.min(100,open.reduce((s,f)=>s+(f.severity==='high'?38:f.severity==='medium'?22:10),0))
  const linkedJob=estimate.linkedJobId?store.jobs.find(j=>j.id===estimate.linkedJobId):undefined
  const closeoutLessons=linkedJob?store.lessons.filter(l=>l.jobId===linkedJob.id):[]
  const pendingLearning=estimate.findingOutcomes.filter(o=>!o.confirmedVerdict).length+closeoutLessons.filter(l=>l.status==='pending').length
  const stageIndex=stages.indexOf(estimate.lifecycleStatus==='lost'?'submitted':estimate.lifecycleStatus)
  return <div className="page">
    {query.warning&&<div className="warning-banner"><AlertTriangle size={16}/><span>{query.warning}</span></div>}
    <div className="page-head"><div><div className="eyebrow">Estimate lifecycle · {estimate.projectType}{estimate.revisionNumber?` · revision ${estimate.revisionNumber}`:''}</div><h1>{estimate.name}</h1>{isDemoOrigin(estimate)&&<Badge tone="pending">Demo sample</Badge>}<p className="subtle">{estimate.location}{estimate.bidDue?` · bid due ${new Date(estimate.bidDue+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'})}`:''}</p></div><div className="actions"><Badge tone={estimate.lifecycleStatus==='learned'?'confirmed':estimate.lifecycleStatus==='lost'?'neutral':'medium'}>{stageLabel(estimate.lifecycleStatus)}</Badge>{['draft','reviewed'].includes(estimate.lifecycleStatus)&&<RerunReview estimateId={estimate.id}/>}<Link className="btn small" href={`/estimates/new?revisionOf=${estimate.id}`}>Create revision</Link></div></div>

    <div className="lifecycle-strip" aria-label="Estimate lifecycle">{stages.map((stage,index)=><div key={stage} className={`lifecycle-step ${index<=stageIndex?'done':''} ${stage===estimate.lifecycleStatus?'current':''}`}><span>{index+1}</span><strong>{stageLabel(stage)}</strong></div>)}{estimate.lifecycleStatus==='lost'&&<div className="lifecycle-step current lost"><span>×</span><strong>Lost</strong></div>}</div>

    <div className="preflight-layout"><div>
      <LifecycleActions estimate={estimate}/>

      {['draft','reviewed'].includes(estimate.lifecycleStatus)&&<section className="section"><div className="section-head"><h2>Preflight findings</h2><span className="helper">Frozen once submitted</span></div>
      {open.length?open.map((finding)=><article className="finding" key={finding.id}><div className="finding-top"><div><Badge tone={finding.severity}>{finding.severity} risk</Badge><h3>{finding.title}</h3></div><FindingActions findingId={finding.id} status={finding.status}/></div><p><strong>{finding.claim}</strong></p><div className="rationale">{finding.rationale}</div><div className="evidence-list"><div className="eyebrow" style={{marginBottom:0}}>Historical evidence</div>{finding.evidence.map((ev)=><div className="evidence" key={`${finding.id}-${ev.jobId}`}><div><strong>{ev.label}</strong><span>{ev.detail}</span></div><Link href={`/jobs/${ev.jobId}`} className="btn small">View job <ExternalLink size={12}/></Link></div>)}</div><div className="recommendation"><strong>Before submission</strong><br/>{finding.recommendation}</div><WarningResponseHistory responses={finding.responses}/></article>):<div className="card empty"><CheckCircle2 size={34} style={{marginBottom:10}}/><h2>No open historical risks</h2><p>Margin Memory did not find a material pattern worth interrupting you about. Continue with your normal estimating review.</p></div>}
      {estimate.findings.some(x=>x.status!=='open')&&<div className="section"><div className="section-head"><h3>Resolved preflight history</h3></div><div className="list">{estimate.findings.filter(x=>x.status!=='open').map((f)=><div className="list-item" key={f.id}><div><div className="list-item-title">{f.title}</div><div className="list-item-meta">{f.status}</div><WarningResponseHistory responses={f.responses}/></div>{f.status!=='superseded'&&<FindingActions findingId={f.id} status={f.status}/>}</div>)}</div></div>}</section>}

      {!['draft','reviewed'].includes(estimate.lifecycleStatus)&&submittedWarnings.length>0&&<section className="section"><div className="section-head"><h2>Submitted warnings and responses</h2></div><p className="helper">The submitted warning record is frozen. Later responses are dated separately and can be recorded until actuals are imported.</p><div className="list">{submittedWarnings.map(finding=><article className="card" key={finding.id}><h3>{finding.title}</h3><p>{finding.claim}</p><div className="recommendation">{finding.recommendation}</div><WarningResponseHistory responses={finding.responses}/>{['submitted','won','in_progress','completed'].includes(estimate.lifecycleStatus)&&<PostSubmissionResponse findingId={finding.id}/>}</article>)}</div></section>}

      {estimate.lifecycleStatus==='completed'&&<section className="section"><CloseoutActualsForm estimateId={estimate.id}/></section>}

      {linkedJob&&<MemoryReadiness jobId={linkedJob.id} estimateId={estimate.id}/>}
      {['learning_review','learned'].includes(estimate.lifecycleStatus)&&<section className="section"><div className="section-head"><div><h2>Did the preflight earn its interruption?</h2><p className="subtle">Compare original warnings with what actually happened. The system result is a review cue; it is not a calibrated probability.</p></div>{estimate.lifecycleStatus==='learning_review'&&<Badge tone={pendingLearning?'pending':'confirmed'}>{pendingLearning} reviews left</Badge>}</div>
        <div className="list">{estimate.findingOutcomes.length?estimate.findingOutcomes.map(outcome=>{const finding=estimate.findings.find(f=>f.id===outcome.findingId);return <div className="card" key={outcome.id}><div className="finding-top"><div><Badge tone={outcome.systemVerdict==='validated'?'high':outcome.systemVerdict==='partially_validated'?'medium':'neutral'}>system: {outcome.systemVerdict.replaceAll('_',' ')}</Badge><h3 style={{marginTop:10}}>{finding?.title??'Historical warning'}</h3></div><div className="helper">Deterministic closeout review · not calibrated</div></div><p>{outcome.explanation}</p><div className="rationale">{outcome.evidenceSummary}</div><div style={{marginTop:12}}><FindingOutcomeActions outcomeId={outcome.id} current={outcome.confirmedVerdict} assessment={outcome.assessment} responses={finding?.responses??[]}/></div></div>}):<div className="card empty">This preflight had no warnings to score. There is nothing to confirm.</div>}</div>
      </section>}

      {['learning_review','learned'].includes(estimate.lifecycleStatus)&&linkedJob&&<section className="section"><div className="section-head"><div><h2>Lessons from the outcome</h2><p className="subtle">Only confirmed lessons enter company memory for future preflights.</p></div><Link className="btn small" href={`/jobs/${linkedJob.id}`}>Open completed job</Link></div><div className="list">{closeoutLessons.length?closeoutLessons.map(lesson=><div className={`lesson ${lesson.status==='pending'?'pending':''}`} key={lesson.id}><div className="finding-top"><div><Badge tone={lesson.status==='confirmed'?'confirmed':lesson.status==='pending'?'pending':'neutral'}>{lesson.status}</Badge><h3 style={{marginTop:9}}>{lesson.title}</h3></div><div className="helper">Observed variance · human review required</div></div><p><strong>{lesson.lesson}</strong></p><p className="subtle">Cause: {lesson.cause}</p><div className="recommendation">Observed impact: {lesson.impactSummary}</div>{lesson.status==='pending'&&<LessonActions lessonId={lesson.id}/>}</div>):<div className="card empty">No material new lesson was proposed from this closeout.</div>}</div></section>}
    </div>

    <aside className="aside-stack">
      <div className="summary-card"><div className="eyebrow" style={{color:'#a8b7ad'}}>Agent preflight</div><div className="score"><strong>{open.length?riskScore:'✓'}</strong><span className="subtle">{open.length?'attention score':'clear'}</span></div><p>{estimate.agentSummary||'Run a preflight to investigate this estimate.'}</p><div className="subtle" style={{fontSize:12}}>{estimate.agentMode==='strands'?'The agent selected the evidence to investigate.':estimate.agentMode==='deterministic'?'Historical rules review used. ':'No investigation has run yet.'}</div>{estimate.agentMode==='strands'&&estimate.agentTelemetry&&<details className="agent-trace"><summary>Investigation details</summary><strong>{estimate.agentTelemetry.cycleCount} agent cycles · {estimate.agentTelemetry.toolsUsed.length} tools</strong>{estimate.agentTelemetry.toolsUsed.length>0&&<div className="tool-chips">{estimate.agentTelemetry.toolsUsed.map((name)=><span key={name}>{name.replaceAll('_',' ')}</span>)}</div>}</details>}</div>
      <div className="card"><div className="eyebrow">Commercial record</div><div className="list"><div><div className="metric-label">Estimate</div><div className="metric-value">{money(estimate.estimatedTotal)}</div></div>{estimate.submittedAmount!==undefined&&<div><div className="metric-label">Submitted</div><strong>{money(estimate.submittedAmount)}</strong></div>}{estimate.contractValue!==undefined&&<div><div className="metric-label">Contract value</div><strong>{money(estimate.contractValue)}</strong></div>}{linkedJob&&<div><div className="metric-label">Final actual cost</div><strong>{money(linkedJob.actualTotal)}</strong></div>}</div></div>
      <div className="card"><div className="eyebrow">Evidence files</div><div className="list">{documents.map(doc=><div key={doc.id}><div className="list-item-title" style={{fontSize:13}}>{doc.fileName}</div><div className="list-item-meta">{doc.kind.replace('_',' ')}</div>{doc.url&&<a href={doc.url} target="_blank" rel="noreferrer" className="helper">Open original ↗</a>}</div>)}</div>{!documents.length&&<div className="helper">No project files attached.</div>}</div>
      {estimate.questions.filter(q=>!q.resolvedAt).map((q)=><div className="question" key={q.id}><Badge tone="medium"><Clock3 size={12}/>needs your input</Badge><h3 style={{marginTop:10}}>{q.prompt}</h3><p className="subtle">{q.context}</p><AnswerQuestion estimateId={estimate.id} questionId={q.id} options={q.options}/></div>)}
      <div className="card"><div className="eyebrow">Lifecycle audit</div><div className="timeline-mini">{events.slice(-8).map((event)=><div key={event.id}><strong>{stageLabel(event.to_stage as LifecycleStatus)}</strong><span>{new Date(event.created_at).toLocaleDateString()}</span>{event.note&&<small>{event.note}</small>}</div>)}</div></div>
      <div className="card"><div className="eyebrow">Trust boundary</div><p className="subtle" style={{marginBottom:10}}><ShieldCheck size={16} style={{verticalAlign:'text-bottom',marginRight:6}}/>The agent can investigate and recommend. It cannot change your price or submit the bid.</p><div className="helper"><AlertTriangle size={13} style={{verticalAlign:'text-bottom',marginRight:4}}/>Every displayed numerical finding must originate from deterministic TypeScript tools.</div></div>
    </aside></div>
  </div>
}
