import { OutcomeAssessmentSummary } from '@/components/warning-response-fields'
import { ScopeSummary } from '@/components/scope-summary'
import { jobScopeComparison } from '@/lib/domain/scope'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { Badge } from '@/components/ui'
import { money } from '@/lib/domain/analytics'
import {isDemoOrigin} from '@/lib/domain/demo'
import { getJob, listDocuments, listLineSourceTraces, readStore } from '@/lib/repository/store'

export const dynamic = 'force-dynamic'

export default async function JobPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const [job, store, documents,traces] = await Promise.all([getJob(id), readStore(), listDocuments({jobId:id}),listLineSourceTraces({jobId:id})])
  if (!job) notFound()
  const lessons = store.lessons.filter((x) => x.jobId === job.id)
  const sourceEstimate=job.sourceEstimateId?store.estimates.find(e=>e.id===job.sourceEstimateId):undefined
  const comparison = jobScopeComparison(job)
  const totalVariance = comparison?.costDeltaPct ?? null
  return <div className="page">
    <div className="page-head"><div><div className="eyebrow">Completed job {isDemoOrigin(job)?'· demo sample':sourceEstimate?'· closed loop':'· legacy import'}</div><h1>{job.name}</h1>{isDemoOrigin(job)&&<Badge tone="pending">Demo · excluded from trusted memory</Badge>}<p className="subtle">{job.projectType} · {job.location} · completed {new Date(`${job.completedAt}T12:00:00`).toLocaleDateString()}</p></div>{sourceEstimate&&<Link className="btn primary" href={`/estimates/${sourceEstimate.id}`}>Open original estimate lifecycle</Link>}</div>
    <div className="grid cols-4"><div className="card"><div className="metric-label">Original cost budget</div><div className="metric-value">{money(job.estimatedTotal)}</div></div><div className="card"><div className="metric-label">Actual cost · all scope</div><div className="metric-value">{money(job.actualTotal)}</div></div><div className="card"><div className="metric-label">Scope-adjusted variance</div><div className={`metric-value ${(totalVariance ?? 0) > .05 ? 'variance-pos' : 'variance-good'}`}>{totalVariance === null ? '—' : `${totalVariance >= 0 ? '+' : ''}${Math.round(totalVariance * 100)}%`}</div></div><div className="card"><div className="metric-label">Gross margin</div><div className="metric-value">{job.scopeReview?.status==='no_changes'&&job.grossMarginPct!==undefined?`${Math.round(job.grossMarginPct*100)}%`:'—'}</div><div className="metric-note">{job.scopeReview?.status!=='no_changes'?'Final change-order revenue is not reconciled':job.contractValue?`on ${money(job.contractValue)} contract`:'Contract value not recorded'}</div></div></div>
    <section className="section"><div className="section-head"><h2>{comparison?'Scope-adjusted budget vs actual':'Original budget vs actual · scope unverified'}</h2></div><div className="table-wrap"><table><thead><tr><th>Category</th><th>{comparison?'Adjusted cost budget':'Original cost budget'}</th><th>Actual cost</th><th>Cost variance</th><th>{comparison?'Adjusted hours':'Original hours'}</th><th>Actual hours</th></tr></thead><tbody>{(comparison?.variances ?? job.variances).map((v) => <tr key={v.category}><td><strong style={{ textTransform: 'capitalize' }}>{v.category}</strong></td><td>{money(v.estimatedCost)}</td><td>{money(v.actualCost)}</td><td className={(v.costDeltaPct || 0) > .05 ? 'variance-pos' : 'variance-good'}>{v.costDeltaPct === null ? '—' : `${v.costDelta >= 0 ? '+' : ''}${Math.round(v.costDeltaPct * 100)}%`}</td><td>{v.estimatedHours || '—'}</td><td>{v.actualHours || '—'}</td></tr>)}</tbody></table></div></section>
    <ScopeSummary job={job}/>
    {sourceEstimate&&<section className="section"><div className="section-head"><h2>Original warning outcomes</h2></div><div className="list">{sourceEstimate.findingOutcomes.length?sourceEstimate.findingOutcomes.map(o=>{const finding=sourceEstimate.findings.find(f=>f.id===o.findingId);return <div className="list-item" key={o.id}><div><div className="list-item-title">{finding?.title??'Margin Check warning'}</div><div className="list-item-meta">Calculated review: {o.systemVerdict.replaceAll('_',' ')} · Estimator review: {o.confirmedVerdict?.replaceAll('_',' ')??'pending verification'}</div>{o.assessment&&<OutcomeAssessmentSummary assessment={o.assessment}/>}</div><Badge tone={o.confirmedVerdict==='validated'?'high':o.confirmedVerdict==='partially_validated'?'medium':o.confirmedVerdict?'neutral':'pending'}>{o.confirmedVerdict?.replaceAll('_',' ')??'pending'}</Badge></div>}):<div className="card empty">The original Margin Check had no warnings to review.</div>}</div></section>}
    <section className="section"><div className="section-head"><h2>Source files</h2></div><div className="list">{documents.length?documents.map((doc)=><div className="list-item" key={doc.id}><div><div className="list-item-title">{doc.fileName}</div><div className="list-item-meta">{doc.kind.replace('_',' ')} · {Math.max(1,Math.round(doc.sizeBytes/1024))} KB</div></div>{doc.url&&<a className="btn small" href={doc.url} target="_blank" rel="noreferrer">Open file</a>}</div>):<div className="card empty">No source files are attached to this job.</div>}</div></section>
    {traces.length>0&&<section className="section"><details className="card"><summary>Line source trace ({traces.length} lines)</summary><p className="helper">Each imported fact remains linked to its reviewed file, worksheet, source row, mapping, and parser version.</p><div className="list">{traces.slice(0,100).map(trace=><div className="list-item" key={`${trace.lineKind}-${trace.lineId}`}><div><div className="list-item-title">{trace.fileName}</div><div className="list-item-meta">{trace.worksheet} · row {trace.sourceRow} · {trace.lineKind.replace('_',' ')}</div></div></div>)}</div>{traces.length>100&&<div className="helper">Showing the first 100 source links.</div>}</details></section>}
    <div className="grid cols-2 section"><div className="card"><div className="eyebrow">Closeout notes</div><p style={{ whiteSpace: 'pre-wrap' }}>{job.notes || 'No notes were imported.'}</p><div className="helper">Tags: {job.tags.join(' · ') || 'none'}</div></div><div><div className="section-head"><h2>Lessons from this job</h2></div><div className="list">{lessons.length ? lessons.map((lesson) => <div className={`lesson ${lesson.status === 'pending' ? 'pending' : ''}`} key={lesson.id}><Badge tone={lesson.status === 'confirmed' ? 'confirmed' : lesson.status==='pending'?'pending':'neutral'}>{lesson.status}</Badge><h3 style={{ marginTop: 9 }}>{lesson.title}</h3><p>{lesson.lesson}</p><div className="helper">{lesson.impactSummary}</div></div>) : <div className="card empty">No lesson has been retained from this job.</div>}</div></div></div>
  </div>
}
