import {it,expect} from 'vitest'
import {EvidenceLedger,calculateRisk,renderAgentOutput,type ToolEvidence} from '../src/lib/agent/provenance'
import {seedStore} from '../src/lib/seed'
const job={...seedStore.jobs[0],id:crypto.randomUUID()}
async function fixture(){const saved:ToolEvidence[]=[];const ledger=new EvidenceLedger(crypto.randomUUID(),async e=>{saved.push(e)});await ledger.record({kind:'search',toolName:'search_similar_jobs',result:{jobIds:[job.id]}});const calc=await ledger.record({kind:'calculation',toolName:'calculate_category_risk',result:calculateRisk([job],'labor')});const raw={findings:[{category:'labor',severity:'high',action:'access',calculationRefs:[calc.id],jobEvidenceRefs:[] as string[]}],questions:[]};return{ledger,raw,saved,calc}}
it('rejects unknown calculation IDs',async()=>{const{ledger,raw}=await fixture();raw.findings[0].calculationRefs=[crypto.randomUUID()];expect(()=>renderAgentOutput(raw,ledger)).toThrow()})
it('rejects calculations from another investigation',async()=>{const a=await fixture();const b=await fixture();a.raw.findings[0].calculationRefs=[b.calc.id];expect(()=>renderAgentOutput(a.raw,a.ledger)).toThrow()})
it('rejects arbitrary job refs and unsearched jobs',async()=>{const{ledger,raw}=await fixture();raw.findings[0].jobEvidenceRefs=[job.id];expect(()=>renderAgentOutput(raw,ledger)).toThrow();const empty=new EvidenceLedger(crypto.randomUUID(),async()=>{});const calc=await empty.record({kind:'calculation',toolName:'calculate_category_risk',result:calculateRisk([job],'labor')});raw.findings[0].jobEvidenceRefs=[];raw.findings[0].calculationRefs=[calc.id];expect(()=>renderAgentOutput(raw,empty)).toThrow('not retrieved')})
it('renders facts only from persisted calculations and rejects numerical overrides',async()=>{const{ledger,raw,saved}=await fixture();const output=renderAgentOutput(raw,ledger);expect(output.findings[0].claim).toBe('1 of 1 completed jobs exceeded the scope-adjusted labor budget by more than 5%.');expect(saved).toHaveLength(2);expect(()=>renderAgentOutput({...raw,findings:[{...raw.findings[0],claim:'5 of 7 jobs overran 23%'}]},ledger)).toThrow()})
it('renders evidence strength and its limitation from the deterministic calculation',async()=>{const{ledger,raw}=await fixture();const output=renderAgentOutput(raw,ledger);expect(output.findings[0].rationale).toContain('Evidence strength: Insufficient.');expect(output.findings[0].rationale).toContain('not a calibrated probability')})
it('does not accept output unless evidence persistence succeeds',async()=>{const ledger=new EvidenceLedger(crypto.randomUUID(),async()=>{throw new Error('database down')});await expect(ledger.record({kind:'search',toolName:'search_similar_jobs',result:{jobIds:[job.id]}})).rejects.toThrow('database down');expect(ledger.all()).toEqual([])})
it('ledger snapshots cannot be mutated by tool consumers',async()=>{const{ledger,calc}=await fixture();if(calc.kind!=='calculation')throw new Error('wrong kind');calc.result.overrunCount=99;const stored=ledger.get(calc.id);expect(stored.kind==='calculation'&&stored.result.overrunCount).toBe(1)})
